name: Deploy to Cloud VPS
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          port: ${{ secrets.VPS_SSH_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "."
          target: "${{ secrets.VPS_PROJECT_PATH }}"

      - name: Create .env file on VPS
        uses: appleboy/ssh-action@master #Executing remote command
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          port: ${{ secrets.VPS_SSH_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            echo "NODE_ENV=production" > ${{ secrets.VPS_PROJECT_PATH }}/.env
            echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" >> ${{ secrets.VPS_PROJECT_PATH }}/.env
            echo "SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}" >> ${{ secrets.VPS_PROJECT_PATH }}/.env
            # TODO altri secrets qui
  
      - name: Start server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          port: ${{ secrets.VPS_SSH_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ${{ secrets.VPS_PROJECT_PATH }}
            npm install
            npm run build
            pm2 restart ${{ secrets.PROJECT_NAME }} || pm2 start npm --name "${{ secrets.PROJECT_NAME }}" -- run start
