name: Deploy to Cloud VPS
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  deploy:    
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Copy repository contents via scp
        uses: appleboy/scp-action@master
        env:
            HOST: ${{ secrets.VPS_SSH_HOST }}
            USERNAME: ${{ secrets.VPS_SSH_USERNAME }}
            PORT: ${{ secrets.VPS_SSH_PORT }}
            KEY: ${{ secrets.VPS_SSH_KEY }}
            PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        with:
            source: "."
            target: "${HOME}/${PROJECT_NAME}"
    
      - name: Executing remote command
        uses: appleboy/ssh-action@master
        env:
            PROJECT_NAME: ${{ secrets.PROJECT_NAME }}
        with:
          host: ${{ secrets.VPS_SSH_HOST }}
          username: ${{ secrets.VPS_SSH_USERNAME }}
          port: ${{ secrets.VPS_SSH_PORT }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: npm install;
            npm run build;
            pm2 restart ${PROJECT_NAME} || pm2 start npm --name "${PROJECT_NAME}" -- run start
